version: '3.9'

services:
  app:
    container_name: asadal_pay_tz_app
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn app.main:app
      --host 0.0.0.0 --port 8000
      --use-colors
      --reload --log-level debug
      "
    volumes:
      - .:/home/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: asadal_pay_tz_db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - fastapi_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    healthcheck:
      test: [
              "CMD-SHELL", "pg_isready -d $PG_DB -U $PG_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  fastapi_postgres_data: {}